services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - default_network
    depends_on:
      - postgres
      - redis
    command: "fastapi dev app.py --host 0.0.0.0"

  postgres:
    image: postgres:17.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default_network

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default_network

volumes:
  postgres_data:
  redis_data:

networks:
  default_network:
