"""Adicionar coluna rating na tabela order

Revision ID: a7f9d69492ab
Revises: a0c4db552383
Create Date: 2025-06-12 22:45:11.090951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f9d69492ab'
down_revision: Union[str, None] = 'a0c4db552383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('orderitem_order_id_fkey'), 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key(op.f('orderitem_order_id_fkey'), 'orderitem', 'order', ['order_id'], ['id'])
    op.drop_column('order', 'rating')
    # ### end Alembic commands ###
